language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
  - PASSWORD=$DOCKER_PASSWORD make docker_build
deploy:
  provider: heroku
  app: vast-savannah-42215
  api_key: ${HEROKU_API_KEY}
